# Generated by Django 4.1.6 on 2023-02-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_remove_order_tax_delete_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item",
                to="payments.discount",
            ),
        ),
    ]
